version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      - COUCHBASE_CONNECTION_STRING=couchbase://couchbase
      - COUCHBASE_USERNAME=fethi
      - COUCHBASE_PASSWORD=112233
      - COUCHBASE_BUCKET_NAME=user_bucket

  couchbase:
    build:
      context: ./couchbase
    ports:
      - "8091:8091" # Web arayüzü
      - "8092:8092" # Query Service
      - "8093:8093" # Index Service
      - "11210:11210" # Data Service
    volumes:
      - couchbase_data:/opt/couchbase/var
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: password

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/pools"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  couchbase_data:
