server:
  port: 8080

spring:
  couchbase:
    connection-string: ${COUCHBASE_CONNECTION_STRING:couchbase://127.0.0.1}
    username: ${COUCHBASE_USERNAME:fethi}
    password: ${COUCHBASE_PASSWORD:112233}
    bucket: ${COUCHBASE_BUCKET_NAME:user_bucket}
  data:
    couchbase:
      auto-index: true

security:
  authentication:
    jwt:
      base64-secret: NGY5MjNlMjFkMWQ4MjQ0NWQ1ODhjZTA4ZjIxZjUyMGM5YzRjNDEwMmE4MzUwODFhNzNjNzE1YjA5OWUxZDZkZWU2ZWE5NDRhODhiYTIwNzc1MGZkNDk5ZmJmMTUzYmU0ODY1YzA1MjIxMzcwZWZiMmI0NDMxOTQ0NGY4MDQ4Y2Q=
      # type of below values are seconds
      token-validity-in-seconds: 28800 #8 hours